name: Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build using compose file
      run: docker compose build

    - name: Tag the image
      run: |
        docker tag bookhub ${{ secrets.DOCKERHUB_USERNAME }}/bookhub:latest
        docker tag bookhub ${{ secrets.DOCKERHUB_USERNAME }}/bookhub:${{ github.run_number }}

    - name: Push the image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookhub:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookhub:${{ github.run_number }}
